### PR TITLE
Added a new filter: Rendering -> Equation Plot [Implicit]

### PR DESCRIPTION
**Pull request by cl4cnam**

### CODE REVIEW

**Comment by Reptorian1125** [comment]
I edited your code to make it easier to read. Test it, and then if it works the same, I'll push it.

**Comment by dtschump** [comment]
Just FYI, I've given the writing access to this repository to @cl4cnam, as he is a long-time contributor with high quality filters. I see no reasons why he still has to create PRs to add new filters.

**Comment by cl4cnam** [comment]
Thanks, David :)

**Comment by Reptorian1125** [comment]
I merged this for you. You can set up git after this. If you need help with that, don't hesitate to reach out at discuss.pixls.us.

**Pull request merged**
